#%RAML 1.0 DataType
type: object
properties: 
  firstName: 
    type: string
    required: true
  lastName: 
    type: string
    required: false
  address: 
    type: string
    required: false
  postal: 
    type: string
    required: false
  country: 
    type: string
    required: false
  accountType: 
    type: string
    required: true
  miles: 
    type: integer
    required: false