#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          {"message":"Resource not found"}
  500:
    body:
      application/json:
        example:
          {"message":"Server Error"}
    