#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/f1bfb7c0-370c-43ea-b6c2-5ec56bbf7513 # 
title: SongDoubleQuate
resourceTypes: 
  collection:
    usage: This API is used by <<resourcePathName>>
    description: API is used to retrieve and create <<resourcePathName>>
    get:
      description: This API is used to retrieve all details about <<resourcePathName>>
      responses: 
        200:
          body: 
            application/json:
              example: |
                <<exampleReference2>>
    post:
      description: This API is used to create <<resourcePathName>>
      body: 
        application/json:
          example: |
            <<exampleReference2>>
      responses: 
        201:
          body: 
            application/json:
              example: |
                {"message":"<<resourcePathName>> created"}
/songs:
  type: 
    collection:
        exampleReference1: |
          {"Songs":[
          {"SongID":1,"SongName":"London Dreams"},
          {"SongID":2,"SongName":"German Whip"}
          ]}
        exampleReference2: |
          {"SongID":1,"SongName":"London Dreams","Singer":"David"}
/artists:
  type:
    collection:
        exampleReference1: |
          {"Artists":[
          {"ArtistID":1,"ArtistName":"David"},
          {"ArtistID":2,"ArtistName":"John"}
          ]}
        exampleReference2: |
          {"ArtistID":1,"ArtistName":"John","D.O.B":"27 July 1978"}