#%RAML 1.0 ResourceType
type:
  shopping.getCollection:
    response-get-type: shopping.products
    response-get-examples: !include ../examples/productExample.raml
    error-trait-get: shopping.errorTrait 