#%RAML 1.0 ResourceType
type:
  shopping.getCollection:
    response-get-type: shopping.categories
    response-get-examples: !include ../examples/categoryExample.raml
    error-trait-get: shopping.errorTrait 