#%RAML 1.0 NamedExample
value:  
- date_joined:
    date: 0
    day: 0
    hours: 0
    minutes: 0
    month: 0
    nanos: 0
    seconds: 0
    time: 0
    timezoneOffset: 0
    year: 0
  deleted: true
  email: string
  modified:
    date: 0
    day: 0
    hours: 0
    minutes: 0
    month: 0
    nanos: 0
    seconds: 0
    time: 0
    timezoneOffset: 0
    year: 0
  type: 0
  userid: 0
  username: string

  
