#%RAML 1.0 SecurityScheme
type: Pass Through
describedBy:
  queryParameters:
    userName:
      displayName: User Name
      description: API key to authorize requests.
    password:
      displayName: Password
      description: API key to authorize requests.