#%RAML 1.0 ResourceType

get:
  description: Retrive all <<resourcePathName>>
  responses:
    200:
      body:
        application/json:
          example: <<get-by-id-response-example>>

            
        
