#%RAML 1.0 NamedExample
value:
    - firstName: "John"
      lastName: "Smith"
      address: "1002 Main Street, Springfield TX"
      postal: "77002"
      country: "USA"
      accountType: "personal"
      miles: 8492
