#%RAML 1.0 NamedExample
value: 
- id: "1"
  firstName: "John"
  lastName: "Smith"
  address: "1002 Main Street, Springfield TX"
  postal: "77002"
  country: "USA"
  creationDate: "2016-01-04T12:48:19+00:00"
  accountType: "personal"
  miles: 8492
- id: "2"
  firstName: "Annabelle"
  lastName: "Simpson"
  address: "20230 Boobear Blvd, Los Angeles CA"
  postal: "94201"
  country: "USA"
  creationDate: "2017-04-30T14:12:25+00:00"
  accountType: "personal"
  miles: 61844
- id: "3"
  firstName: "Bjorn"
  lastName: "Yeti"
  address: "18491 Instant Ave, Cleveland OH"
  postal: "238301-7481"
  country: "USA"
  creationDate: "2017-01-03T04:48:14+00:00"
  accountType: "personal"
  miles: 1948