#%RAML 1.0 NamedExample
value:
- categoryid: 100
  description: DELL
  name: Laptop
  price: 2000
  productid: 101
  video_url: https://www.dell.com/en-us/shop/dell-laptops/sc/laptops
- categoryid: 300
  description: DELL
  name: Laptop
  price: 1000
  productid: 150385
  video_url: https://www.dell.com/en-us/shop/dell-laptops/sc/laptops