#%RAML 1.0 NamedExample
value:
  productid: 101
  categoryid: 54
  name: KK G-707 Gaming mouse
  description: The G-707 Gaming mouse is a razor-sharp mouse with 3000 DPI. The mouse comes with a 1-year warranty 
  video_url: https://www.dell.com/en-us/shop/dell-laptops/sc/laptops 
  price: 1000