#%RAML 1.0
--- 
title: e-BookMobile API
/users:
  /authors:
    /{authorname}:
/books:
  get:
  put:
  post:
  /{bookTitle}:
    get:
    post:
    put:
    delete:
    /author:
      get:
    /pupublisher:
      get:
      