#%RAML 1.0 Library
usage:
types:
  RequestBookData:
    properties:
      id:
        default: 
        displayName: ID
      title:
        default: "Stiff: The Curious Lives of Human Cadavers"
        displayName: Title
      description:
        default: null
        displayName: DescriptionTitle
      datetime:
        type: date-only
        default: 2000-02-02
        displayName: Date Time
      genre:
        default: "science"
        displayName: Genre
      author:
        default: "Mary Roach"
        displayName: Author
      link:
        displayName: Link
        default: "http://e-bookmobile.com/books/Stiff"
  ResponseBookData:
    properties:
      title:
        default: "Stiff: The Curious Lives of Human Cadavers"
        displayName: Title
      description:
        default: null
        displayName: DescriptionTitle
      datetime:
        type: date-only
        default: 2000-02-02
        displayName: Date Time
      genre:
        default: "science"
        displayName: Genre
      author:
        default: "Mary Roach"
        displayName: Author
      link:
        displayName: Link
        default: "http://e-bookmobile.com/books/Stiff"


    
    
    
      

      